# -*- coding: utf-8 -*-
"""VAR(1)_LDL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nz4VyxpbV10TnOTmjiPmywCqyy8uSAfy
"""

import numpy as np

A = np.random.rand(8,8)
K = np.matmul(A,np.transpose(A))
d = int(len(K)/2)
L = np.zeros((2*d,2*d))
D = np.zeros((2*d,2*d))

for j in range(d):
  if j == 0:
    D[0,0] = K[0,0]
  else:
    sum = 0
    for h in range(j):
      sum += L[j,h]*D[h,h]*L[j,h]
    D[j,j] = K[j,j] - sum

  for i in range(j+1,d):
    sum = 0
    for h in range(j):
      sum += L[i,h]*D[h,h]*L[j,h]
    L[i,j] = (K[i,j] - sum)/D[j,j]

  L[d:,j] = K[d:,j]
  for h in range(j):
    L[d:,j] -= D[h,h]*L[j,h]*L[d:,h]
  L[d:,j] = L[d:,j]/D[j,j]

for i in range(int(2*d)):
  L[i,i] = 1
                
D[d:,d:] = np.linalg.inv(np.linalg.inv(K)[d:,d:])

print(K)

print(L)

print(D)

print(np.matmul(L,np.matmul(D,np.transpose(L))))

print(np.zeros((2,1)))

